- name: Play book to use ios_config module and config directly to device1
  hosts: all
  connection: local
  gather_facts: no

  tasks:
  - name: NSO global variables
    include_vars:
      file: nso.yaml
      name: nso

  - name: configure interface settings
    ios_config:
      provider: "{{ nso.cli }}"
      lines:
      - description my new desc
      parents: interface Loopback244

  - name: Cisco Webex Teams - Markdown Message to a Room
    community.general.cisco_webex:
      recipient_type: roomId
      recipient_id: "{{ nso.room }}"
      msg_type: markdown
      personal_token: "{{ nso.token }}"
      msg: "**config-cli job: config has been executed successfully**"
