- name: Play book to use ios_config module and config device directly
  hosts: all
  connection: local
  gather_facts: no

  vars:
    cli:
      username: admin
      password: Wireless123

  tasks:
  - name: NSO global variables
    include_vars:
      file: nso.yaml
      name: nso

  - name: configure interface settings
    ios_config:
      provider: "{{ cli }}"
      lines:
      - description is connfigure via Jenkins through ios module
      parents: interface Loopback244

  - name: Cisco Webex Teams - Markdown Message to a Room
    community.general.cisco_webex:
      recipient_type: roomId
      recipient_id: Y2lzY29zcGFyazovL3VzL1JPT00vOTczMjM0MzAtYjJmYS0xMWViLWJlN2YtZWJiMWM0MjQ5YTVm
      msg_type: markdown
      personal_token: YTNlZGU0N2EtYTFjOC00Nzg4LTkxOGMtYzkyMjlmMTBlZmI1ZWIwMWQ4MjUtOTAz_PF84_1eb65fdf-9643-417f-9974-ad72cae0e10f
      msg: "**Above ios configuration job has been executed successfully**"
