- name: Play book to use ios_config module and config device directly
  hosts: all
  connection: local
  gather_facts: no

  vars:
    cli:
      username: admin
      password: Wireless123

  tasks:
  - name: NSO global variables
    include_vars:
      file: nso.yaml
      name: nso

  - name: configure interface settings
    ios_config:
      provider: "{{ cli }}"
      lines:
      - demo to Mohan
      parents: interface Loopback244
